Checkpoint

diff --git a/scripts/backup-lvm-libvirt b/scripts/backup-lvm-libvirt
--- a/scripts/backup-lvm-libvirt
+++ b/scripts/backup-lvm-libvirt
@@ -18,27 +18,42 @@ function check_space_available() { # 1:lv_size
     #
     # Returns code 0 if space is available, or 1 if not.
     #
+    local target_space_available
+
     target_space_available=$(df --sync -BG "${backup_target}" | sed '1d' \
     | awk '{print $2}' | tr -d 'G')
+    logger -p user.debug "${script_name}: lv_size: $1."
+    logger -p user.debug "${script_name}: target_space_available: ${target_space_available}."
+
     if [[ "${target_space_available}" -lt "$1" ]]; then
-        return 1
+        logger -p user.info "${script_name}: Not enough space available on \
+${backup_target}. Exiting."
+        exit 1
     else
+        logger -p user.info "${script_name}: Adequate space available on \
+${backup_target}"
         return 0
     fi
 }
 
 function get_lv_paths() { # 1:vm_name
     #
-    # Returns array of lv absolute paths associated with vm_name (except
+    # Creates array of lv absolute paths associated with vm_name (except
     # devices listed in exclusions).
+    # (Initially returned an array, but was too difficult to do properly).
     #
     # TODO: set exclusions via optional argument.
     #
-    local exclusions, string_paths
+    local exclusions string_paths
     exclusions='cdrom'
+
     string_paths=$(virsh domblklist --details "$1" | grep -Ev \
     "${exclusions}" | sed '1,2d' | sed '$,1d' | awk '{print $4}')
+    logger -p user.debug "${script_name}: string_paths: ${string_paths}."
+
     array_paths=( "${string_paths}" )
+    logger -p user.info "${script_name}: LVs associated with VM: \
+${array_paths[*]}."
 }
 
 function get_lv_size() { # 1:lv_path
@@ -46,9 +61,16 @@ function get_lv_size() { # 1:lv_path
     # Return the size in GB of lv_path.
     #
     local size
-    size="$(lvs --noheadings --units g -o lv_name,seg_size "$1" | awk \
-    '{print $2}' | tr -d 'g')"
-    printf "%s" "${size}"
+
+    if size="$(lvs --noheadings --units g -o lv_name,seg_size "$1" | awk \
+    '{print $2}' | tr -d 'g')"; then
+        intsize=${size%.*}
+        logger -p user.debug "${script_name}: intsize: ${intsize}."
+        printf "%s" "${intsize}"
+    else
+        logger -p user.err "${script_name}: Failed to retrieve LV size. Exiting"
+        exit 1
+    fi
 }
 
 function get_vg_name() { # 1:lv_path
@@ -56,8 +78,14 @@ function get_vg_name() { # 1:lv_path
     # Return the name of vg from lv_path.
     #
     local name
-    name="$(lvs --noheadings -o vg_name $1)"
-    printf "%s" "${name}"
+
+    if name="$(lvs --noheadings -o vg_name $1)"; then
+        logger -p user.debug "${script_name}: vg_name: ${name}."
+        printf "%s" "${name}"
+    else
+        logger -p user.err "${script_name}: Could not obtain VG name. Exiting."
+        exit 1
+    fi
 }
 
 #
@@ -66,45 +94,57 @@ function get_vg_name() { # 1:lv_path
 
 # Validate.
 
-[[ -d "${backup_target}" ]] || { printf "%s is not a directory" \
-"${backup_target}"; exit 1; }
+[[ -d "${backup_target}" ]] || { printf "%s does not exist or is not a \
+directory" "${backup_target}"; exit 1; }
 
 script_name="$(basename $0)"
 [[ $# = 1 ]] || { printf "%s vm_name" "${script_name}"; exit 1; }
 
-# Get absolute paths of all lvs associated with vm_name.
+# Populate array_paths with absolute paths of all lvs associated with vm_name.
 get_lv_paths "$1"
 
 # Create hash of lv paths + sizes in GB.
 declare -A lv_sizes
-
-for path in ${array_paths[@]}; do
-    lv_sizes[${path}]=$(get_lv_size ${path})
-done
-
-# Print results (debug).
-for lv in ${!lv_sizes[@]}; do
-    printf "Volume %s is %s GB.\n" "${lv}" "${lv_sizes[${lv}]}"
+for path in "${array_paths[@]}"; do
+    size=$(get_lv_size "${path}")
+    logger -p user.debug "${script_name}: ${path} size: ${size}."
+    lv_sizes["${path}"]="${size}"
+    logger -p user.info "${script_name}: Added \[${path}: ${size}\] to hash."
 done
 
 # Create snapshot for each LV.
 snapshots=()
 for lv in ${!lv_sizes[@]}; do
-    check_space_available "${lv_sizes[${lv}]}" || { printf "Not enough space \
-    available on %s to backup %s. Exiting.\n" "${backup_target}" "${lv}"; exit 1; }
+    logger -p user.info "${script_name}: Checking if space is available."
+    check_space_available "${lv_sizes[${lv}]}" 
 
+    logger -p user.info "${script_name}: Obtaining VG name."
     vg_name=$(get_vg_name ${lv})
+
+    logger -p user.info "${script_name}: Creating LV snapshot."
     lvcreate -L"${lv_sizes[${lv}]}" -s -n "${path#\/dev\/${vg_name}\/}.snap" \
     "${lv}"
     snapshots+=("${path#\/dev\/${vg_name}\/}.snap")
 done
 
 # Use dd to copy snapshot to target filesystem.
-for snap in ${snapshots[@]}; do
-    dd if="${snap}" of="${backup_target}/${snap}.$(date +%Y-%m-%d-%H%M).img"
+for snap in "${snapshots[@]}"; do
+    logger -p user.notice "${script_name}: Copying ${snap} to ${backup_target}/${snap}.$(date +%Y-%m-%d-%H%M).img"
+
+    #if dd if="${snap}" of="${backup_target}/${snap}.$(date +%Y-%m-%d-%H%M).img"; then
+    #    logger -p user.debug "${script_name}: Copy succeeded."
+    #else
+    #    logger -p user.err "${script_name}: Copy failed."
+    #fi
 done
 
 # Delete snapshots.
-for snap in ${snapshots[@]}; do
-    lvremove "${snap}"
+for snap in "${snapshots[@]}"; do
+    logger -p user.notice "${script_name}: Removing snapshot ${snap}."
+
+    #if lvremove "${snap}"; then
+    #    logger -p user.debug "${script_name}: ${snap} removed."
+    #else
+    #    logger -p user.warn "${script_name}: Removal of ${snap} failed."
+    #fi
 done
