Tests if IP changes required

diff --git a/scripts/re-ip b/scripts/re-ip
--- a/scripts/re-ip
+++ b/scripts/re-ip
@@ -7,6 +7,10 @@
 # This script does not and should not change resolv.conf, as resolvers in both
 # sites should be configured.
 
+# TODO:
+# Split found_old_prefixes test out into a function.
+# Should require more than 1 failed ping to trigger actions.
+
 primary_net='10.110.73'
 primary_gateway='10.110.73.1'
 dr_net='192.168.2'
@@ -79,51 +83,79 @@ function restart_networking_ubuntu() { # 1:os_version
 
 
 #===============================================================================
-# Update Configuration.
+# Update IP address(es).
 #===============================================================================
 
-function update_hosts_file() { # 1:old_network, 2:new_network
-    log "Changing network from $1 to $2 on all entries in /etc/hosts."
-    sed -i "s/$1/$2/g" /etc/hosts
+function update_file() { # 1:file, 2:old_prefix, 3:new_prefix
+    if ! [[ $(cat "$1") =~ $2 ]]; then
+        log "No IP address updates required."
+        return
+    else
+        log "Changing network prefix from $2 to $3 on all IP addresses in $1."
+        sed -i "s/$2/$3/g" "$1"
+    fi
 }
 
-function update_fstab() { # 1:old_network, 2:new_network
-    log "Changing network from $1 to $2 on all entries in /etc/fstab."
-    sed -i "s/$1/$2/g" /etc/fstab
+function update_ubuntu_12_14_16_interfaces() { # 1:old_prefix, 2:new_prefix
+    found_old_prefixes=$(find /etc/network/interfaces /etc/network/interfaces.d 
+        -type f -exec grep "$1" {} \;)
+
+    if [[ -z ${found_old_prefixes} ]]; then
+        log "No IP address updates required."
+        return
+    else
+        log "Changing network prefix from $1 to $2 on /etc/network/interfaces."
+        sed -i "s/$1/$2/g" /etc/network/interfaces
+
+        log "Collecting network config files."
+        ifcfg_files=($(ls /etc/network/interfaces.d/*.cfg))
+
+        for ((i=0; i<${#ifcfg_files[@]}; i++)); do
+            log "Changing network from $1 to $2 on ${ifcfg_files[i]}."
+            sed -i "s/$1/$2/g" "${ifcfg_files[i]}"
+        done
+    fi
 }
 
-function update_ubuntu_12_14_16_interfaces() { # 1:old_network, 2:new_network
-    log "Changing network from $1 to $2 on /etc/network/interfaces."
-    sed -i "s/$1/$2/g" /etc/network/interfaces
+function update_ubuntu_18_interfaces() { # 1:old_prefix, 2:new_prefix
+    found_old_prefixes=$(find /etc/netplan -type f -name '*.yaml'
+        -exec grep "$1" {} \;)
 
-    log "Collecting network script files."
-    ifcfg_files=($(ls /etc/network/interfaces.d/*.cfg))
-    for ((i=0; i<${#ifcfg_files[@]}; i++)); do
-        log "Changing network from $1 to $2 on ${ifcfg_files[i]}."
-        sed -i "s/$1/$2/g" "${ifcfg_files[i]}"
-    done
+    if [[ -z ${found_old_prefixes} ]]; then
+        log "No IP address updates required."
+        return
+    else
+        log "Collecting network config files."
+        ifcfg_files=($(ls /etc/netplan/*.yaml))
+
+        for ((i=0; i<${#ifcfg_files[@]}; i++)); do
+            log "Changing network prefix from $1 to $2 on ${ifcfg_files[i]}."
+            sed -i "s/$1/$2/g" "${ifcfg_files[i]}"
+        done
+    fi
 }
 
-function update_ubuntu_18_interfaces() { # 1:old_network, 2:new_network
-    ifcfg_files=($(ls /etc/netplan/*.yaml))
-    for ((i=0; i<${#ifcfg_files[@]}; i++)); do
-        log "Changing network from $1 to $2 on ${ifcfg_files[i]}."
-        sed -i "s/$1/$2/g" "${ifcfg_files[i]}"
-    done
+function update_centos_6_7_interfaces() { # 1:old_prefix, 2:new_prefix
+    found_old_prefixes=$(find /etc/sysconfig/network-scripts -type f
+        -name 'ifcfg-*' -exec grep "$1" {} \;)
+
+    if [[ -z ${found_old_prefixes} ]]; then
+        log "No IP address updates required."
+        return
+    else
+        log "Collecting network config files."
+        ifcfg_files=($(ls /etc/sysconfig/network-scripts/ifcfg-*))
+
+        for ((i=0; i<${#ifcfg_files[@]}; i++)); do
+            log "Changing network prefix from $1 to $2 on ${ifcfg_files[i]}."
+            sed -i "s/$1/$2/g" "${ifcfg_files[i]}"
+        done
+    fi
 }
 
-function update_centos_6_7_interfaces() { # 1:old_network, 2:new_network
-    ifcfg_files=($(ls /etc/sysconfig/network-scripts/ifcfg-*))
-    for ((i=0; i<${#ifcfg_files[@]}; i++)); do
-        log "Changing network from $1 to $2 on ${ifcfg_files[i]}."
-        sed -i "s/$1/$2/g" "${ifcfg_files[i]}"
-    done
-}
+function update_config() { # 1:os_vendor, 2:os_version, 3:old_prefix,
+                           # 4:new_prefix}
 
-function update_config() { # 1:os_vendor, 2:os_version, 3:old_network,
-                           # 4:new_network}
-
-    # Update OS/version-specific things first.
     if [[ "$1" == "ubuntu" ]]; then
         case "$2" in
             1[246].04) shift 2; update_ubuntu_12_14_16_interfaces "$@" ;;
@@ -141,9 +173,7 @@ function update_config() { # 1:os_vendor, 2:os_version, 3:old_network,
         esac
     fi
 
-    # Update standard-format things.
-    update_hosts_file "$@"
-    # update_fstab "$@"
+    update_file /etc/hosts "$@"
 }    
 
 
@@ -177,11 +207,11 @@ esac
 ping_gateway "${primary_gateway}"
 if [ $? -eq 0 ]; then
     log "${primary_gateway} is reachable. This VM appears to be on primary \
-    site network. No changes will be applied."
+    network."
     exit 0
 else
     log "${primary_gateway} is not reachable. Assuming we're on the DR site. \
-    Updating network config accordingly."
+    Updating IP address(s) to DR site prefix, if required."
     update_config "${os_vendor}" "${os_version}" "${primary_net}" "${dr_net}"
     restart_networking_"${os_vendor}" "${os_version}"
 fi
@@ -189,12 +219,11 @@ fi
 # Try the DR gateway.
 ping_gateway "${dr_gateway}"
 if [ $? -eq 0 ]; then
-    log "${dr_gateway} is reachable. This VM appears to be on the DR network. \
-    No changes will be applied."
+    log "${dr_gateway} is reachable. This VM appears to be on the DR network."
     exit 0
 else
-    log "${dr_gateway} is not reachable. Something is not right. Reverting to \
-    primary site network config."
+    log "${dr_gateway} is not reachable. Assuming we are on primary network. \
+    Updating IP address(es) to primary site prefix, if required."
     update_config "${os_vendor}" "${os_version}" "${dr_net}" "${primary_net}"
     restart_networking_"${os_vendor}" "${os_version}"
 fi
