Now supports selected guest only backups

diff --git a/scripts/current/backup-libvirt b/scripts/current/backup-libvirt
--- a/scripts/current/backup-libvirt
+++ b/scripts/current/backup-libvirt
@@ -2,43 +2,84 @@
 
 # Back up all libvirt qemu / qcow2 guests.
 
+# TODO: Need to merge these all/selected functions.
+
 images_dir=/var/lib/libvirt/images
 backup_dir=/backups/libvirt
 
 ##
 
-all_guest_fullpaths=()
-while read -r -d ''; do # Preferable to "-d $'\0'".  Could also use IFS= and do away with '-d' altogether.
-  all_guest_fullpaths+=("$REPLY") # Quotes around $REPLY means no fiddling with IFS.
-done < <(sudo find "${images_dir}" -maxdepth 1 -mindepth 1 -type f -print0) # Print results null-separated.
+check_any_active() {
+  active_guests=$(sudo virsh list | sed '1,2d;$d' | awk '{print $2}')
 
-printf "\nThe following guests will be backed up: \n\n"
-printf "%s\n" "$(sudo find ${images_dir} -maxdepth 1 -mindepth 1 -type f -printf '%f\n')"
+  if [[ -n "$active_guests" ]]; then
+    printf "\nSome guests are still running. All guests must be stopped to run this script.\n"
+    exit 0
+  else
+    printf "\nNo guests found running. Jolly good. We shall continue.\n"
+  fi
+}
 
-active_guests=$(sudo virsh list | sed '1,2d;$d')
+check_selected_active() {
+  active_guests=$(sudo virsh list | sed '1,2d;$d' | awk '{print $2}')
 
-if [[ -n "$active_guests" ]]; then
-  printf "\nSome guests are still running. All guests must be stopped to run this script.\n"
-  exit 0
+  for s in "$@"; do
+    if [[ "$active_guests" =~ "$s" ]]; then
+      printf "\nOne or more selected guests are still running. They must be stopped to be backed up.\n"
+      exit 0
+    else
+      printf "\nNo selected guests found running. Jolly good. We shall continue.\n"
+    fi
+  done
+}
+
+backup_all() {
+  printf "\nThe following guests will be backed up: \n\n"
+  all_guest_fullpaths=()
+  while read -r -d ''; do
+    all_guest_fullpaths+=("$REPLY")
+    printf "${REPLY}\n"
+  done < <(sudo find "${images_dir}" -maxdepth 1 -mindepth 1 -type f -print0)
+
+  for fullpath in "${all_guest_fullpaths[@]}"; do
+    guest=$(basename "${fullpath//.qcow2}")
+    printf "\nBacking up ${guest}...\n"
+
+    if [[ ! -d "${backup_dir}/${guest}" ]] || [[ ! -w "${backup_dir}/${guest}" ]]; then
+      mkdir "${backup_dir}/${guest}"
+    fi
+
+    sudo virsh dumpxml "${guest}" > "${backup_dir}/${guest}/${guest}.xml" || \
+      { printf "sudo virsh dumpxml ${guest} failed.\n"; exit 1; }
+
+    sudo rsync -a "${fullpath}" "${backup_dir}/${guest}/${guest}" || \
+      { printf "rsync failed.\n"; exit 1; }
+  
+  done
+}
+
+backup_selected() {
+  for guest in "$@"; do
+    printf "\nBacking up ${guest}..\n"
+
+    if [[ ! -d "${backup_dir}/${guest}" ]] || [[ ! -w "${backup_dir}/${guest}" ]]; then
+      mkdir "${backup_dir}/${guest}"
+    fi
+
+    sudo virsh dumpxml "${guest}" > "${backup_dir}/${guest}/${guest}.xml" || \
+      { printf "sudo virsh dumpxml ${guest} failed.\n"; exit 1; }
+
+    sudo rsync -a "/var/lib/libvirt/images/${guest}.qcow2" "${backup_dir}/${guest}/${guest}" || \
+      { printf "rsync failed.\n"; exit 1; }
+  
+  done
+}
+
+if [[ "$#" -gt 0 ]]; then
+  check_selected_active "$@"
+  backup_selected "$@"
 else
-  printf "\nNo guests found running. Jolly good. We shall continue.\n"
+  check_any_active
+  backup_all
 fi
 
-for fullpath in "${all_guest_fullpaths[@]}"; do
-  guest=$(basename "${fullpath//.qcow2}")
-  printf "\nBacking up ${guest}...\n"
-
-  if [[ ! -d "${backup_dir}/${guest}" ]] || [[ ! -w "${backup_dir}/${guest}" ]]; then
-    mkdir "${backup_dir}/${guest}"
-  fi
-
-  sudo virsh dumpxml "${guest}" > "${backup_dir}/${guest}/${guest}.xml" || \
-    { printf "sudo virsh dumpxml ${guest} failed.\n"; exit 1; }
-
-  rsync -a "${fullpath}" "${backup_dir}/${guest}/${guest}" || \
-    { printf "sudo rsync ${fullpath} failed.\n"; exit 1; }
-
-done
-
-printf "\nDone\n\n"
-printf "%s\n" "$(ls -l ${backup_dir}/* )"
