while/read simplified

diff --git a/scripts/current/btrfs-snapshot b/scripts/current/btrfs-snapshot
--- a/scripts/current/btrfs-snapshot
+++ b/scripts/current/btrfs-snapshot
@@ -1,6 +1,5 @@
 #!/bin/bash
 
-# btrfs-snapshot.sh
 # Snapshots subvolumes listed in 'subvols' array, and deletes old snapshots.
 
 subvols=( '/home/' )
@@ -10,28 +9,27 @@ cur_date=$(date "+%d-%m-%Y")
 die_date=$(date "+%d-%m-%Y" -d "${die_days} days ago")
 
 
-btrfs=$(which btrfs) || \
+btrfs="$(which btrfs)" || \
 { echo "error: could not find btrfs binary" >> /var/log/btrfs/snapshot.log; exit 1; }
 
-take_snapshots()
+function take_snapshots()
 {
   for subvol in ${subvols[@]}
   do
-    $btrfs subvolume snapshot $subvol ${subvol}.snapshots/${cur_date} || \
-    { echo "error: could not create a snapshot of volume $subvol" >> /var/log/btrfs/snapshot.log; exit 2; }
+    ${btrfs} subvolume snapshot ${subvol} ${subvol}.snapshots/${cur_date} || \
+    { echo "Error: could not create a snapshot of volume ${subvol}." >> /var/log/btrfs/snapshot.log; exit 1; }
   done
 }
 
-delete_old_snapshots()
+function delete_old_snapshots()
 {
   for subvol in ${subvols[@]}
   do
     cd ${subvol}.snapshots
-    $btrfs subvolume delete $die_date || \
-    { echo "error: could not delete snapshot of volume $subvol from $die_date" >> /var/log/btrfs/snapshot.log; exit 3; }
+    ${btrfs} subvolume delete ${die_date} || \
+    { echo "error: could not delete snapshot of volume ${subvol} from ${die_date}" >> /var/log/btrfs/snapshot.log; exit 1; }
   done
 }
 
 # Run the thing
-take_snapshots
-delete_old_snapshots
+take_snapshots && delete_old_snapshots
